// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;

// ignore: unused_import
import 'package:flutter/widgets.dart';

// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';

// ignore: unused_import
import 'package:path/path.dart' as path;

// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: fitness_app
  static const package = "fitness_app";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: lib/assets/images/home/person_image_1.png
  // ignore: non_constant_identifier_names
  final person_image_1 = const AssetResource(
      "assets/images/home/person_image_1.png",
      packageName: R.package);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();

  /// asset: lib/assets/images/home/ic_advanced.svg
  // ignore: non_constant_identifier_names
  final ic_advanced = const AssetResource("assets/images/home/ic_advanced.svg",
      packageName: R.package);

  /// asset: lib/assets/images/home/ic_arrow_forward.svg
  // ignore: non_constant_identifier_names
  final ic_arrow_forward = const AssetResource(
      "assets/images/home/ic_arrow_forward.svg",
      packageName: R.package);

  /// asset: lib/assets/images/home/ic_cardiogram.svg
  // ignore: non_constant_identifier_names
  final ic_cardiogram = const AssetResource(
      "assets/images/home/ic_cardiogram.svg",
      packageName: R.package);

  /// asset: lib/assets/images/home/ic_search.svg
  // ignore: non_constant_identifier_names
  final ic_search = const AssetResource("assets/images/home/ic_search.svg",
      packageName: R.package);

  /// asset: lib/assets/images/home/ic_stopwatch.svg
  // ignore: non_constant_identifier_names
  final ic_stopwatch = const AssetResource(
      "assets/images/home/ic_stopwatch.svg",
      packageName: R.package);

  /// asset: lib/assets/images/home/ic_trail_running_shoe.svg
  // ignore: non_constant_identifier_names
  final ic_trail_running_shoe = const AssetResource(
      "assets/images/home/ic_trail_running_shoe.svg",
      packageName: R.package);

  /// asset: lib/assets/images/home/ic_weight.svg
  // ignore: non_constant_identifier_names
  final ic_weight = const AssetResource("assets/images/home/ic_weight.svg",
      packageName: R.package);

  /// asset: lib/assets/images/main/ic_activity.svg
  // ignore: non_constant_identifier_names
  final ic_activity = const AssetResource("assets/images/main/ic_activity.svg",
      packageName: R.package);

  /// asset: lib/assets/images/main/ic_home.svg
  // ignore: non_constant_identifier_names
  final ic_home = const AssetResource("assets/images/main/ic_home.svg",
      packageName: R.package);

  /// asset: lib/assets/images/main/ic_profile.svg
  // ignore: non_constant_identifier_names
  final ic_profile = const AssetResource("assets/images/main/ic_profile.svg",
      packageName: R.package);

  /// asset: lib/assets/images/main/ic_settings.svg
  // ignore: non_constant_identifier_names
  final ic_settings = const AssetResource("assets/images/main/ic_settings.svg",
      packageName: R.package);
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: lib/assets/images/home/person_image_1.png
  // ignore: non_constant_identifier_names
  AssetImage person_image_1() {
    return AssetImage(asset.person_image_1.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();

  /// asset: lib/assets/images/home/ic_advanced.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_advanced({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_advanced.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/home/ic_arrow_forward.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_arrow_forward({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_arrow_forward.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/home/ic_cardiogram.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_cardiogram({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_cardiogram.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/home/ic_search.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_search({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_search.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/home/ic_stopwatch.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_stopwatch({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_stopwatch.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/home/ic_trail_running_shoe.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_trail_running_shoe(
      {@required double width, @required double height}) {
    final imageProvider = AssetSvg(asset.ic_trail_running_shoe.keyName,
        width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/home/ic_weight.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_weight({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_weight.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/main/ic_activity.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_activity({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_activity.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/main/ic_home.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_home({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_home.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/main/ic_profile.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_profile({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_profile.keyName, width: width, height: height);
    return imageProvider;
  }

  /// asset: lib/assets/images/main/ic_settings.svg
  // ignore: non_constant_identifier_names
  AssetSvg ic_settings({@required double width, @required double height}) {
    final imageProvider =
        AssetSvg(asset.ic_settings.keyName, width: width, height: height);
    return imageProvider;
  }
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();

  /// font family: LouisGeorgeCafe
  // ignore: non_constant_identifier_names
  final louisGeorgeCafe = "LouisGeorgeCafe";
}
